name: social
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  auto_route: ^10.1.0+1
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  retrofit: ^4.7.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  curved_labeled_navigation_bar: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.1.0
  retrofit_generator: ^9.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/social-icon.png
    - assets/icons/gallery.svg
    - assets/icons/trending.svg
    - assets/image/post.jpg
    - assets/image/avatar.jpg

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf # 400
  #       - asset: assets/fonts/Roboto-Italic.ttf # 400 italic
  #         style: italic
  #       - asset: assets/fonts/Roboto-Medium.ttf # 500
  #         weight: 500
  #       - asset: assets/fonts/Roboto-MediumItalic.ttf # 500 italic
  #         style: italic
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf # 700
  #         weight: 700
  #       - asset: assets/fonts/Roboto-BoldItalic.ttf # 700 italic
  #         style: italic
  #         weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/social-icon.png"
